#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Self-test for hooks/guard.py: cases that must be blocked (exit 2) and cases that
# must pass (exit 0). Inputs are wrapped the way Claude Code sends them
# ({"tool_name": "Bash", "tool_input": {"command": ..., "description": ...}}).
# SELFTEST_GUARD=/path/to/copy runs the cases against a modified copy.
H="${SELFTEST_GUARD:-$(dirname "$0")/guard.py}"; pass=0; fail=0
t() { local want="$1" cmd="$2" desc="${3:-run a command}" js rc
  js=$(python3 -c 'import json,sys;print(json.dumps({"tool_name":"Bash","tool_input":{"command":sys.argv[1],"description":sys.argv[2]}}))' "$cmd" "$desc")
  case "$H" in *.sh) echo "$js" | bash "$H" >/dev/null 2>&1;; *) echo "$js" | python3 "$H" >/dev/null 2>&1;; esac; rc=$?
  if [ "$rc" = "$want" ]; then pass=$((pass+1)); else fail=$((fail+1)); echo "FAIL want $want got $rc: $cmd / $desc"; fi; }

# --- must block: whole-tree staging
t 2 'git add -A'
t 2 'git add -A && git commit -m "x" -- a'
t 2 'cd /repo && git add .'
t 2 'git add --all'
t 2 'git add --al'
t 2 'git add -u'
t 2 'git add -Av'
t 2 'git add :/'
t 2 'git add "."'
t 2 'cd sub && git add ../.'
t 2 'git add -A 2>&1'
t 2 'git add -A 2>&1 | tail -3'
t 2 'git -C /repo add .'
t 2 'git -C "$HOME/my repo" add -A'
t 2 'git -c core.quotepath=off add -A'
t 2 $'git\tadd\t-A'
t 2 'git add ":!mine"'
# --- must block: committing everything
t 2 'git commit -am "x"'
t 2 'git commit -a -m "x"'
t 2 'git commit -qam "x"'
t 2 'git commit -vam x'
t 2 'git commit --all -m x'
t 2 'git commit -m "x"'
t 2 'git commit --amend --no-edit'
t 2 'git commit -m x -- .'
# --- must block: discarding / sweeping
t 2 'git reset --hard'
t 2 'git reset --hard HEAD~1'
t 2 'git reset --har'
t 2 'git reset'
t 2 'git reset HEAD~1'
t 2 'git reset -- .'
t 2 'git clean -fd'
t 2 'git clean -xdf'
t 2 'git clean --force -d'
t 2 'git stash'
t 2 'git stash push -m "tmp"'
t 2 'git stash -u'
t 2 'git stash 2>&1'
t 2 'git stash >/dev/null'
t 2 'git --no-pager stash'
t 2 'git stash; git pull'
t 2 'git stash drop'
t 2 'git checkout .'
t 2 'git checkout -- .'
t 2 'git checkout HEAD -- .'
t 2 'git checkout -f'
t 2 'git checkout main'
t 2 'git checkout -b feature'
t 2 'git switch main'
t 2 'git restore .'
t 2 'git restore -- .'
t 2 'git restore --staged .'
t 2 'git restore --worktree .'
t 2 'git restore -SW .'
t 2 'git restore --staged --worktree -- .'
t 2 'git rm -r --cached .'
t 2 'echo "$(git stash)"'
t 2 'bash -c "git add -A"'
t 2 "sh -c 'cd sub && git reset --hard'"
t 2 'eval "git stash"'
t 2 'sudo git clean -fdx'
# --- must block: switching off wombat-gate's agent check
t 2 'WOMBAT_HUMAN_OVERRIDE=1 wombat-gate run --unsafe -- stash'
t 2 'export WOMBAT_HUMAN_OVERRIDE=1 && wombat-gate commit --allow-broad -m x -- .'
t 2 'env WOMBAT_HUMAN_OVERRIDE=1 wombat-gate run --unsafe -- stash'
t 2 'env -u CLAUDECODE wombat-gate run --unsafe -- stash'
t 2 'env -uCLAUDECODE wombat-gate run --unsafe -- stash'
t 2 "env -u 'CLAUDECODE' wombat-gate run --unsafe -- stash"
t 2 'env --unset=CLAUDECODE wombat-gate commit --allow-broad -m x -- .'
t 2 'env --unset CLAUDECODE wombat-gate run --unsafe -- stash'
t 2 'unset CLAUDECODE; wombat-gate run --unsafe -- clean -fd'
t 2 'unset "CLAUDECODE"; wombat-gate run --unsafe -- stash'
t 2 'unset FOO CLAUDECODE && wombat-gate run --unsafe -- stash'
t 2 "bash -c \"unset 'CLAUDECODE'; wombat-gate run --unsafe -- stash\""
t 2 'export -n CLAUDECODE; wombat-gate run --unsafe -- stash'
t 2 'declare +x CLAUDECODE && wombat-gate run --unsafe -- stash'
t 2 'typeset +x CLAUDECODE; wombat-gate commit --allow-broad -m x -- .'
t 2 'export CLAUDECODE=0; wombat-gate run --unsafe -- stash'
t 2 'CLAUDECODE= wombat-gate run --unsafe -- stash'
t 2 'CLAUDECODE=0 wombat-gate commit --allow-broad -m x -- .'
t 2 $'unset\tCLAUDECODE; wombat-gate run --unsafe -- stash'
t 2 'env -i PATH=/usr/bin wombat-gate run --unsafe -- stash'
t 2 'env - wombat-gate run --unsafe -- stash'
t 2 'env -iPATH=/usr/bin wombat-gate run --unsafe -- stash'
t 2 'env -0i wombat-gate run --unsafe -- stash'
t 2 'env --ignore-env wombat-gate run --unsafe -- stash'
t 2 'env -u FOO -i wombat-gate run --unsafe -- stash'
t 2 '/usr/bin/env -i PATH=/usr/bin wombat-gate run --unsafe -- stash'
t 2 'nohup env -i wombat-gate run --unsafe -- stash &'
# --- must block: shell keywords in front, comments, generated paths (review round 3)
t 2 'if true; then git add .; fi'
t 2 'if ! git diff --quiet; then git stash; fi'
t 2 'for f in a b; do git stash; done'
t 2 'while true; do git reset --hard; break; done'
t 2 'echo a#b; git add .'
t 2 'git commit -m x -- a#b; git add .'
t 2 'curl -s https://example.com/x#frag; git stash'
t 2 'git commit -i -m x -- a'
t 2 'git commit --include -m x -- a'
t 2 'git commit --amend -m x -- a'
t 2 'git add $(git ls-files -m)'
t 2 'git add "$PWD"'
t 2 'git add "$(git rev-parse --show-toplevel)"'
t 2 'git commit -m x -- "$(pwd)"'
t 2 'git ls-files -m | xargs git add'
t 2 'git ls-files -m | xargs -I {} git add {}'
t 2 'find . -name "*.py" -exec git add {} +'
t 2 'sudo -u me git add .'
t 2 'timeout -s KILL 60 git stash'
t 2 'nice -n 10 git clean -fdx'
t 2 'git pull'
t 2 'git pull --rebase origin main'
t 2 'git merge feature'
t 2 'git rebase main'
t 2 'git checkout-index -a -f'
t 2 'git read-tree -u --reset HEAD'
t 2 "$(printf 'nohup %.0s' $(seq 20))git status"
t 2 "$(printf 'nohup %.0s' $(seq 3000))git status"
# --- must block: review round 4
t 2 'git clean --f'
t 2 'git clean -d --f'
t 2 'git commit --am -m x -- a'
t 2 'git add --pathspec-from-file=list.txt'
t 2 'git rm --pathspec-from-file=list.txt'
t 2 'exec -c wombat-gate run --unsafe -- stash'
t 2 'setsid env -i wombat-gate run --unsafe -- stash'
t 2 'printf -v CLAUDECODE 0; wombat-gate run --unsafe -- stash'
t 2 'read CLAUDECODE <<< 0; wombat-gate run --unsafe -- stash'
# --- must pass: everyday commands on your own paths
t 0 'git add src/parser.py tests/test_parser.py'
t 0 'git add -A -- src/mine'
t 0 'git add -u src/mine'
t 0 'git add --all -- src'
t 0 'git add -p src/x.py'
t 0 'git status --short -- src'
t 0 'git status'
t 0 'git commit -m "fix: x" -- src/parser.py'
t 0 'git commit -m "support -a flag" -- src/x.py'
t 0 'git commit -m "-a" -- src/x.py'
t 0 'git commit --dry-run -m x'
t 0 'git log --oneline -5'
t 0 'git diff --stat -- src'
t 0 'git stash list'
t 0 'git stash show -p stash@{0}'
t 0 'git reset -q -- src/x.py'
t 0 'git checkout -- src/x.py'
t 0 'git restore --staged src/x.py'
t 0 'git restore -- src/x.py'
t 0 'git clean -fd src/mine/build'
t 0 'git rm --cached src/old.py'
t 0 'ls -a .'
t 0 'wombat-gate commit -m "parser: x" -- src/parser'
t 0 'wombat-gate commit -m "docs: never use --allow-broad or --unsafe" -- docs'
t 0 'wombat-gate commit -m "docs: WOMBAT_HUMAN_OVERRIDE is for humans" -- docs'
t 0 'wombat-gate status -uno -- src'
t 0 'wombat-gate run -- git push'
t 0 'wombat-gate who'
t 0 'grep -n -- --unsafe README.md'
t 0 "grep -n 'CLAUDECODE=' README.md"
t 0 'grep -rn WOMBAT_HUMAN_OVERRIDE src'
t 0 'echo "CLAUDECODE is $CLAUDECODE"'
t 0 'printenv CLAUDECODE; env | grep -c CLAUDE'
t 0 'env FOO=1 grep -i pattern file.txt'
t 0 'env PYTHONPATH=. python3 x.py -i 3'
t 0 'env -u FOO python3 x.py'
t 0 'conda env list'
t 0 'env -h'
t 0 'uv run --env-file .env python3 x.py'
t 0 'docker run -e FOO=1 img'
t 0 $'cat > msg.txt <<\'EOF\'\ndocs: explain why we never run\ngit stash\nin a shared tree\nEOF\nwombat-gate commit -F msg.txt -- src'
t 0 'echo "git stash" > notes.txt'
t 0 'git commit -m "$(cat msg)" -- src/x.py'
t 0 $'git commit -m "$(cat <<\'EOF\'\nfix: parser\n\nlonger body\nEOF\n)" -- src/x.py'
t 0 'git commit -m "$(cat m)" -m "$(cat n)" -- src/a src/b'
t 0 'git commit -F "$(mktemp)" -- src/x.py'
t 0 'git clean -fd src/mine/build'
t 0 'exec python3 x.py'
t 0 'printf "%s\n" "$CLAUDECODE"'
t 0 'git commit -m "see #12" -- src/x.py'
t 0 "git commit -m 'a; git add .' -- src/x.py"
t 0 'git commit -F msg.txt -- src/x.py'
t 0 'git checkout -- src/a.py src/b.py'
t 0 'git log -p -- .'
t 0 'git status -- .'
t 0 'git diff'
t 0 'git mv src/a.py src/b.py'
t 0 'git rm src/old.py'
t 0 'git add src/a.py src/b.py'
t 0 'for f in src/a.py src/b.py; do git add "$f"; done'
t 0 'if git diff --quiet -- src; then echo clean; fi'
t 0 'git fetch origin && git log origin/main -3'
t 0 'git push origin main'
t 0 'echo done # git stash would be bad here'
t 0 'git ls-files | xargs wc -l'
t 0 'find src -name "*.pyc" -exec rm {} +'
# --- must pass: the words only appear in the description
t 0 'wombat-gate commit -m x -- src/a' 'explain WOMBAT_HUMAN_OVERRIDE is human-only'
t 0 'wombat-gate status -- src/a' 'check whether CLAUDECODE= is blocked'
t 0 'git status --short -- src' 'never run git add -A or git stash here'
t 0 'ls' 'note to self: env -i would hide CLAUDECODE'
# --- documented: spellings of wombat-gate's own flags are left to wombat-gate itself
t 0 'wombat-gate run "--unsafe" -- stash'
t 0 $'wombat-gate commit -m x \\\n--allow-broad -- .'
echo "selftest_guard: $((pass+fail)) cases, $pass ok, $fail failed"; [ "$fail" = 0 ]
